[package]
name = "restserver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3"
dht22_pi = { version = "0.3", path = "../dht22_pi" }
once_cell = "1.10"
