#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly TARGET_ARCH=arm-unknown-linux-gnueabihf
readonly TARGET_HOST=pi@10.3.141.1
readonly TARGET_PATH=/home/pi/restserver/restserver
readonly SOURCE_PATH=./target/${TARGET_ARCH}/release/restserver

cargo build --release --target=${TARGET_ARCH}
rsync ${SOURCE_PATH} ${TARGET_HOST}:${TARGET_PATH}
# ssh -t ${TARGET_HOST} ${TARGET_PATH}
